name: Snyk example 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: "1.18"
    - uses: actions/checkout@v3
    - uses: snyk/actions/setup@master
    - name: Run Snyk to check for vulnerabilities
      run: snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
